# Generated by Django 3.2.15 on 2022-09-03 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_afconleague_baseball_bundesliga_championleague_englishpremierleague_europaleague_formula1_laliga_nba'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Afcon',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.afconleague'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Baseball',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.baseball'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Bundesliga',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.bundesliga'),
        ),
        migrations.AddField(
            model_name='profile',
            name='EnglishPremierLeague',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.englishpremierleague'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Europa',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.europaleague'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Formula1',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.formula1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Laliga',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.laliga'),
        ),
        migrations.AddField(
            model_name='profile',
            name='NBA',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.nba'),
        ),
        migrations.AddField(
            model_name='profile',
            name='NFL',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.nfl'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Team',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.championleague'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Worldcup',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.worldcup'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
