# Generated by Django 3.2.15 on 2022-09-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220903_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clubimage',
            field=models.ImageField(choices=[('Manchester', 'Manchester'), ('Arsenal', 'Arsenal'), ('Liverpool', 'Liverpool'), ('Chelsea', 'Chelsea'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='Manchester', max_length=220, upload_to=''),
        ),
    ]
