# Generated by Django 3.2.15 on 2022-10-11 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_clubimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Afcon',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.afconleague'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Baseball',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.baseball'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Bundesliga',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.bundesliga'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='EnglishPremierLeague',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.englishpremierleague'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Europa',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.europaleague'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Formula1',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.formula1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Laliga',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.laliga'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='NBA',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.nba'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='NFL',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.nfl'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Team',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.championleague'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Worldcup',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.worldcup'),
        ),
    ]
