# Generated by Django 3.2.15 on 2022-10-11 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20221011_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Worldcup',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.worldcup'),
        ),
    ]
