# Generated by Django 3.2.15 on 2022-10-09 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Laliga', '0003_auto_20221009_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaligaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoname', models.CharField(max_length=50)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('about', models.TextField(max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentLaligaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=275)),
                ('uploadedvideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laliga_uploadedvideo', to='Laliga.laligavideo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
