# Generated by Django 3.2.15 on 2022-10-09 06:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Worldcup', '0003_auto_20221009_0903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentWorlpcupVideo',
            new_name='CommentWorldcupVideo',
        ),
    ]
